def calculate_shanten(hand: list[int], num_melds: int) -> int: ...
def calculate_ukeire(hand: list[int], num_melds: int, visible: list[int]) -> tuple[int, int]: ...
def compute_riichi_features(hand: list[int], num_melds: int, visible: list[int]) -> tuple[float, float, float]: ...
def batch_compute_riichi_features(hands: list[list[int]], num_melds: list[int], visible: list[list[int]]) -> list[tuple[float, float, float]]: ...
